# Generated by Django 5.2 on 2025-07-06 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_cartitem_customeraddress_payment_productreview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery',
            field=models.DateField(),
        ),
    ]
