# Generated by Django 5.2.1 on 2025-07-11 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_estimated_delivery'),
    ]



    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Black', 'Black'), ('White', 'White')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 7, 18, 10, 32, 29, 793603, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('PR', 'Processing'), ('S', 'Shipped'), ('D', 'Delivered'), ('C', 'Cancelled')], default='PR', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobiles', 'Mobiles'), ('Watches', 'Watches'), ('Smartwatches', 'Smartwatches'), ('Laptops', 'Laptops'), ('Electronics', 'Electronics Gadgets'), ('FASIONS', 'fasions'), ('Men', 'Men Fashion'), ('Women', 'Women Fashion'), ('Kids', 'Kids Fashion'), ('Footwear', 'Footwear')], max_length=50),
        ),
    ]
