# Generated by Django 5.2.1 on 2025-07-17 18:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_color_product_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FashionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='fashion/categories/')),
            ],
            options={
                'verbose_name_plural': 'Fashion Categories',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 7, 24, 18, 11, 54, 696351, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobiles', 'Mobiles'), ('Watches', 'Watches'), ('Smartwatches', 'Smartwatches'), ('Laptops', 'Laptops'), ('Electronics', 'Electronics Gadgets')], max_length=50),
        ),
        migrations.CreateModel(
            name='FashionSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.fashioncategory')),
            ],
            options={
                'verbose_name_plural': 'Fashion Subcategories',
            },
        ),
        migrations.CreateModel(
            name='FashionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gender', models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('K', 'Kids'), ('U', 'Unisex')], max_length=1)),
                ('size', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='fashion/products/')),
                ('stock', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.fashioncategory')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.fashionsubcategory')),
            ],
        ),
    ]
