# Generated by Django 5.2 on 2025-07-20 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_fashioncategory_remove_product_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashionsubcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fashionproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fashionproduct',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Black', 'Black'), ('White', 'White'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Gray', 'Gray'), ('Brown', 'Brown')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large'), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 7, 27, 12, 55, 24, 651554, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobiles', 'Mobiles'), ('Watches', 'Watches'), ('Smartwatches', 'Smartwatches'), ('Laptops', 'Laptops'), ('Electronics', 'Electronics Gadgets'), ('Fashions', 'Fashions'), ('Men', 'Men Fashion'), ('Women', 'Women Fashion'), ('Kids', 'Kids Fashion'), ('Footwear', 'Footwear')], max_length=50),
        ),
        migrations.DeleteModel(
            name='FashionCategory',
        ),
        migrations.DeleteModel(
            name='FashionProduct',
        ),
        migrations.DeleteModel(
            name='FashionSubCategory',
        ),
    ]
